### ISSUE TITLE
Enable Non-free algorithms?

### ISSUE THREAD

**Issue by flatsiedatsie** [thortex/rpi3-opencv#9]
Apparently it would speed up things a bit if you enable non-free algorithms. Or is this not compatible?

**Comment by thortex** [comment]
You can enable non-free algorithms by adding -D OPENCV_ENABLE_NONFREE=ON into OpenCV cmake option.

I would not release binaries with non-free algorithms.

**Comment by flatsiedatsie** [comment]
That makes sense. Thanks.

**Comment by thortex** [comment]
thnx to your close.
